=== OrcaBus/service-case-manager/case-manager/app/schemas/events/CaseRelationshipUpdate.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/OrcaBus/case-manager/refs/heads/main/case-manager/app/schemas/events/case_external_entity_relationship_created.json",
  "description": "EventBridge event schema for updates to relationships between cases and external entities.",
  "title": "CaseRelationshipUpdateEvent",
  "type": "object",
  "required": ["detail-type", "detail", "source"],
  "properties": {
    "id": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "enum": ["orcabus.casemanager"]
    },
    "time": {
      "type": "string",
      "format": "date-time"
    },
    "version": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "detail-type": {
      "type": "string"
    },
    "detail": {
      "$ref": "#/definitions/CaseRelationshipUpdate"
    }
  },
  "definitions": {
    "CaseRelationshipUpdate": {
      "type": "object",
      "required": ["action", "addedVia", "case", "externalEntity"],
      "properties": {
        "action": {
          "type": "string",
          "enum": ["CREATE", "DELETE"]
        },
        "addedVia": {
          "type": "string"
        },
        "case": {
          "type": "object"
        },
        "externalEntity": {
          "type": "object"
        }
      }
    }
  }
}

=== OrcaBus/service-case-manager/case-manager/app/schemas/events/examples/case_entity_relation_create_1.json
{
  "version": "0",
  "id": "8d891dc9-df3f-0cec-a6d9-650388dd07be",
  "detail-type": "CaseRelationshipStateChange",
  "source": "orcabus.casemanager",
  "account": "843407916570",
  "time": "2025-09-05T07:31:41Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "action": "CREATE",
    "addedVia": "manual",
    "case": {
      "orcabus_id": "cas.01K4CAZ6M86JFFHB863WVASNJ6",
      "title": "string",
      "description": "string",
      "type": "string",
      "last_modified": "2025-09-05T07:03:05.614595Z"
    },
    "externalEntity": {
      "orcabus_id": "39GFXYE80JTMD7RZ7EBKW4S8R4",
      "prefix": "lib",
      "type": "library",
      "service_name": "metadata",
      "alias": "L001"
    }
  }
}
